bdloc_app:
    resource: "@BdlocAppBundle/Controller/"
    type:     annotation
    prefix:   /


bdloc_app_subscribe:
    resource: "@BdlocAppBundle/Controller/SubscribeController.php"
    type:     annotation
    prefix:   /subscribe/


