security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: login_check
            logout:
                path: /logout
                target: /

        default:
            anonymous: ~

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        main:
            entity: { class: Bdloc\AppBundle\Entity\User }

    encoders:
        Bdloc\AppBundle\Entity\User:
            algorithm:   sha512
            iterations: 5000
            encode_as_base64: false       